apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: DSM_ADMIN
          value: "{{ .Values.setup.dsmAdmin }}"
        - name: DSM_ADMIN_PWD
          value: "{{ .Values.setup.dsmAdminPwd }}"
        - name: DSM_REPODB_IP
          value: "{{ .Values.setup.repoDB.IP }}"
        - name: DSM_REPODB_PORT
          value: "{{ .Values.setup.repoDB.port }}"
        - name: DSM_REPODB_USER
          value: "{{ .Values.setup.repoDB.user }}"
        - name: DSM_REPODB_PWD
          value: "{{ .Values.setup.repoDB.pwd }}"
        - name: DSM_REPODB_NAME
          value: "{{ .Values.setup.repoDB.name }}"
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: 180
        readinessProbe:
          initialDelaySeconds: 180
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
